# Basic
title: Anttu
author: Anttu
subtitle: ä¸ªäººç«™
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Anttu
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Java | linux
url: "https://anttutu.github.io"

# Comment
#comment:
    # disqus: 
    # duoshuo: 
    # youyan: 2135147

# gitment
gitment: 
         id: 8287a6ac1cb424dd8ff0
         secret: 49e0050abbf6ed5581940a7a85db9465dbe29ac5

# Social
social:
    weibo: 5574617638
    github: anTtutu
    csdn: anttu
    # twitter: 
    mail: anttu0531@gmail.com
    # gplus: anttu0531

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: f840ee1cf94942747467436f33412e09  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
   id: UA-101226804-1    
   host: auto  

# Github
github:
   user: anTtutu
   repo: anTtutu.github.io

# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/anTtutu/anTtutu.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/

markdown: kramdown

kramdown:
  input:  GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge

# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: å½’æ¡£, description: archive, url: '/archive'}   
    - {title: åˆ†ç±», description: tags, url: '/tags'}
    - {title: ç•™è¨€, description: messages, url: '/messages'}      
    - {title: å…³äº, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"
